// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	markerProgMarkSocket = "mark_socket"
)

// loadMarker returns the embedded CollectionSpec for marker.
func loadMarker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MarkerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load marker: %w", err)
	}

	return spec, err
}

// loadMarkerObjects loads marker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*markerObjects
//	*markerPrograms
//	*markerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMarkerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadMarker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// markerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markerSpecs struct {
	markerProgramSpecs
	markerMapSpecs
	markerVariableSpecs
}

// markerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markerProgramSpecs struct {
	MarkSocket *ebpf.ProgramSpec `ebpf:"mark_socket"`
}

// markerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markerMapSpecs struct {
}

// markerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markerVariableSpecs struct {
}

// markerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMarkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type markerObjects struct {
	markerPrograms
	markerMaps
	markerVariables
}

func (o *markerObjects) Close() error {
	return _MarkerClose(
		&o.markerPrograms,
		&o.markerMaps,
	)
}

// markerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMarkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type markerMaps struct {
}

func (m *markerMaps) Close() error {
	return _MarkerClose()
}

// markerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMarkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type markerVariables struct {
}

// markerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMarkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type markerPrograms struct {
	MarkSocket *ebpf.Program `ebpf:"mark_socket"`
}

func (p *markerPrograms) Close() error {
	return _MarkerClose(
		p.MarkSocket,
	)
}

func _MarkerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed marker_bpfel.o
var _MarkerBytes []byte
